FROM golang:alpine as build

WORKDIR /usr/src/app

COPY go.mod ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/app ./...

FROM hello-world

COPY --from=build /usr/local/bin/app /usr/local/bin/app

CMD ["app"]